modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="eventlens"
version="1.2.2"
displayName="EventLens"
description='''Optional EventLens client mod for diagnosing mod event handlers. Companion to the Paper plugin.'''

[[dependencies.eventlens]]
modId="neoforge"
type="required"
versionRange="[21.1.244,)"
ordering="NONE"
side="CLIENT"

[[dependencies.eventlens]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="CLIENT"
