modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="eventlens"
version="1.10.5-beta"
displayName="EventLens"
description='''Optional EventLens client mod for diagnosing mod event handlers. Companion to the Paper plugin.'''

[[dependencies.eventlens]]
modId="neoforge"
type="required"
versionRange="[26.2.0.59,)"
ordering="NONE"
side="CLIENT"

[[dependencies.eventlens]]
modId="minecraft"
type="required"
versionRange="[26.2]"
ordering="NONE"
side="CLIENT"
