pluginManagement {
    repositories {
        mavenCentral()
        gradlePluginPortal()
        maven {
            name = 'neoforged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'fabricmc'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'minecraftforge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}

rootProject.name = 'EventLens'

include(
        'eventlens-core',
        'eventlens-paper',
        'eventlens-observability',
        'eventlens-agent',
        'eventlens-testkit'
)

boolean paperOnly = providers.gradleProperty('eventlens.paperOnly').getOrElse('false') == 'true'
if (!paperOnly) {
    include(
            'eventlens-client-agent',
            'eventlens-mod-common',
            'eventlens-neoforge',
            'eventlens-forge',
            'eventlens-fabric',
            'eventlens-setup'
    )
}

dependencyResolutionManagement {
    repositories {
        mavenCentral()
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            name = 'neoforged'
            url = 'https://maven.neoforged.net/releases'
        }
        maven {
            name = 'fabricmc'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'minecraftforge'
            url = 'https://maven.minecraftforge.net/'
        }
    }
}
