modLoader="javafml"
loaderVersion="[65,)"
license="MIT"
clientSideOnly=true

[[mixins]]
config="eventlens.mixins.json"

[[mods]]
modId="eventlens"
version="1.10.3-beta"
displayName="EventLens"
description='''Optional EventLens client mod for diagnosing Forge event handlers. Companion to the Paper plugin.'''

[[dependencies.eventlens]]
modId="forge"
mandatory=true
versionRange="[65.1.0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.eventlens]]
modId="minecraft"
mandatory=true
versionRange="[26.2]"
ordering="NONE"
side="CLIENT"
