package dev.bellaouzo.eventlens.domain.conflict;

public enum ConflictKind {
    CANCELLATION_FIGHT,
    MULTI_PLUGIN_PROPERTY_CHANGE,
    PROPERTY_REVERTED,
    POST_CANCEL_LISTENER,
    MONITOR_MUTATION,
    DUPLICATE_REGISTRATION,
    EQUIVALENT_LISTENER,
    LISTENER_EXCEPTION,
    SLOW_LISTENER_CHAIN
}
